baseURL: https://shruti2062.github.io/
languageCode: en-us
build:
  writeStats: true
params:
  title: Shruti's Portfolio
  author: Shruti Sharma
  description: Website title
  theme:
    mainTheme: light
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Shruti Sharma"
    tagline: Research Scholar
    location: "India"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/shruti-sharma-592075226"
        title: LinkedIn
      - icon: fab fa-orcid
        url: "https://orcid.org/0009-0005-4259-7348"
        title: Orcid
      - icon: ai ai-google-scholar
        url: "https://scholar.google.com/citations?user=8KN7rKQAAAAJ&hl=en"
        title: Google Scholar
      - icon: fab fa-researchgate
        url: "https://www.researchgate.net/profile/Shruti-Sharma-124?ev=hdr_xprf"
        title: ResearchGate
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: I am currently pursuing a Ph.D. in the field of nanoscience and technology, focusing on the synthesis and characterization of Carbon Quantum Dots (CQDs) using cost-effective techniques with various non-toxic green and organic precursors. To enhance their efficiency and stability, these CQDs are capped with organic polymers. My research explores their applications in nanosensors, bioimaging, and light-emitting devices.  Additionally, I validate my experimental findings through Density Functional Theory (DFT) simulations using Gaussian software. I have published eight research papers, including six as the first author in reputed journals, and have presented my work at multiple national and international conferences. 
  experience:
    title: Conferences/ Workshops/ Summer Schools
    icon: fas fa-briefcase
    list:
      - position: Conferences
        details: |1-
          - Poster presentation on “Turn on-off switching of leaf-derived carbon quantum dots for selective detection of Zn2+ and Fe3+ ions” in Conference in Innovations in Materials Science & Workshop on Characterization Techniques (IMAT), 2024 organised by Institute Instrumentation Centre, Indian Institute of Technology Roorkee (IIT Roorkee), 24th-27th April, 2024.
          - Oral presentation on “Synthesis and Characterization of Bio-Derived Carbon Quantum Dots for the Detection of Heavy Metal Ions” in Raman Optronics Webinar Series-2023 (ROWS’23) organized by Raman International Optronics Society (RIOS) in association with the Department of Optoelectronics, University of Kerala, India and LELS, University of Nova Gorica, Solvenia. 07th-30th November, 2023. 
          - Oral presentation on “Synthesis and Characterization of Bio-Derived Photoluminescent Carbon Quantum Dots” in International Conference on Energy & Advanced Materials  (ICEAM-2023) organized by Department of Physics and Materials Science & Engineering, Jaypee Institute of Information Technology, Noida. 02th-04th November, 2023.
          - Oral presentation on “Photoluminescent Carbon Quantum Dots Synthesized from Natural Resources and their applications as metal ion sensor” in International Conference on Materials for Energy and Sustainable Development (MESD), 2023 organised by School of Physical Sciences, Jawaharlal Nehru University (JNU), New Delhi. 27th-29th October, 2023.
          - Oral presentation on “Fluorescence signal from carbon quantum dots synthesized from natural resources” in International Conference on Advanced Materials and Nanotechnology (ICAMN), 2022 organized by Department of Physics and Materials Science & Engineering, Jaypee Institute of Information Technology, Noida. 22nd-24th December, 2022.
      - position: Workshops
        details: |1-
          - Attended online workshop on “Functional Materials and Simulation Techniques (FMST 2024)” organized by the Department of Applied Sciences, Indian Institute of Information Technology Allahabad (IIITA), from 21st to 25th October 2024.
          - Attended offline “Workshop on Advanced Materials and Sustainable Energy (WAMSE 2024)” organized by Department of Physics and Materials Science & Engineering, Jaypee Institute of Information Technology, Noida, from 16th to17th November 2024.
          - Attended ‘Second International Quantum Communication Conclave' organized by Telecommunication Engineering Centre (TEC) in association with C-DOT and TSDSI on 15-16 February, 2024 at Vigyan Bhawan, New Delhi.
          - Attended three days Workshop on Advanced Materials for Batteries (WAMB)-2024 organized by Department of Physics and Materials Science & Engineering, Jaypee Institute of Information Technology, Noida. 19th-21st February, 2024.
          - Indian Nanoelectronics Users’ Program- Idea to Innovation (INUP-i2i) online Familiarization Workshop on Nanofabrication and Characterization, held by Indian Institute of Technology Kharagpur (IIT Kharagpur), 22nd-24th April, 2024.
          - Awareness Program on Advance Material and their Application 2.0 (AMA 2.0) workshop organized by University of Petroleum and Energy Studies (UPES), Dehradun. 24th-26th August, 2023.
      - position: Summer Schools
        details: |1-
          - Participated in Vigyan Vidushi 2021, a TIFR Advanced Programme in Physics for women students in first year M.Sc. during May 31 to June 19,2021.
          - Participated in the Summer School 2021 Programme held during July 12-16, 2021 conducted online at INDIAN INSTITUTE OF ASTROPHYSICS Bengaluru, India.
          - Selected to attend the virtual Introductory Summer School in Astronomy and Astrophysics organised by IUCAA.

  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Ph.D. in Physics
        college: Jaypee Institute of Information Technology, Noida secor-62, Uttar Pradesh, India
        dates: 2022 - Present
        thesis_title: "Carbon Quantum Dots (CQDs) synthesis, characterization and applications."
        thesis_url: "#"
      - degree: M.Sc. in Physics 
        college: Kirorimal College, University of Delhi, New Delhi India
        dates: 2020 - 2022
        thesis_title: "Proton acceleration from laser-solid interaction via pic simulations."
        thesis_url: "#"
      - degree: B.S. in Physics (Honours)
        college: Shaheed Rajguru College of Applied Sciences for Women, University of Delhi, New Delhi, India
        dates: 2017 - 2020
  publication:
    title: Publications (Patent, Journal Articles, Proceedings)
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Patent
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Green Synthesis And Characterisation Of Green Carbon Quantum Dots (GCQDs) From Bargad /Banyan Leaves (Ficus Benghalensis).
        authors: "Papia Chowdhury and Shruti Sharma"
        date: "02/06/2023 (published)"
        journal: "Application number- 202311027723"
        url: "https://iprsearch.ipindia.gov.in/publicsearch"
        type: Patent
      - title: >-
          Harvesting Nature's Brilliance: Iron Ion (Fe3+) Sensing by Plumeria obtusa Leaf-Derived Carbon Quantum Dots.
        authors: "Shruti Sharma, Amisha Bhardwaj, Narayanan Venkatakrishnan, Papia Chowdhury"
        date: "2024"
        journal: "Arabian Journal for Science and Engineering"
        url: "https://doi.org/10.1007/s13369-024-09815-8"
        type: Journal Articles
      - title: >-
          Reactivities of 4-amino salicylic acid and its ‘Green’inhibition into nano sized β-cyclodextrin for Anti-Tuberculosis drug delivery.
        authors: "Shruti Sharma, Pooja Yadav, Meenakshi Rana, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Molecular Liquids, 410, 125611"
        url: "https://doi.org/10.1016/j.molliq.2024.125611"
        type: Journal Articles
      - title: >-
          Photoluminescent carbon quantum dots synthesized from Plumeria leaves as metal ion sensor.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Bulletin of Materials Science 47 (3), 187"
        url: "https://doi.org/10.1007/s12034-024-03273-6"
        type: Journal Articles
      - title: >-
          Tunable dual photoluminescence from synthesized urea-based carbon quantum dots: A DFT based simulation on structural insights.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Optical Materials, 153, 115617"
        url: "https://doi.org/10.1016/j.optmat.2024.115617"
        type: Journal Articles
      - title: >-
          Thioglycolic acid capped CdSe/ZnS quantum dot as fluorescent sensor for the detection of water-soluble hazardous heavy metal ions.
        authors: "Shruti Sharma, Pooja Yadav, Papia Chowdhury"
        date: "2024"
        journal: "Applied Physics A 130 (5), 1-12"
        url: "https://doi.org/10.1007/s00339-024-07491-x"
        type: Journal Articles
      - title: >-
          Two-photon absorption and optical limiting in 7-diethylamino-4-methyl coumarin.
        authors: "Shradha Lakhera, Kamal Devlal, Meenakshi Rana, N Kanagathara, A Dhanusha, TC Sabari Girisun, Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry 447, 115216"
        url: "https://doi.org/10.1016/j.jphotochem.2023.115216"
        type: Journal Articles
        type: Journal Articles
      - title: >-
          Exploring the nonlinear optical limiting activity of para-aminobenzoic acid by experimental and DFT approach.
        authors: "Shradha Lakhera, Meenakshi Rana, Kamal Devlal, Shruti Sharma, Papia Chowdhury, Vivek Dhuliya, Sagar Panwar, LP Purohit, A Dhanusha, TC Sabari Girisun"
        date: "2023"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry, 444, 114987"
        url: "https://doi.org/10.1016/j.jphotochem.2023.114987"
        type: Journal Articles
      - 
        title: >-
          Fluorescence signal from carbon quantum dots synthesized from natural resources.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2023"
        journal: "Materials Today: Proceedings"
        url: "https://doi.org/10.1016/j.matpr.2023.05.676"
        type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Data Analysis on Time-of-Flight study from the data files of Fermilab's to find Muon's Speed 
        url: "#"
        description: Data Analysis on Time-of-Flight study from the data files of Fermilab's to find Muon's Speed during International Muon Week. In this project we used the data of stacked detectors in Fermilab Location- Batavia, Illinois [ latitude- 41:52.193794 N, longitude- 087:38.902188 W (same for both)] which are placed at different positions upon each other. We determined the speed by calculating the inverse of the slopes of the best fit lines in scatter plots (where the independent variable is separation(m) and the dependent variable is mean traversal time (ns)). We compared our results for different pair of detectors. Looking at our results ,we concluded with our hypothesis to be true where muon speeds are found to be close to speed of light. 
      - title: Project
        url: "#"
        description: 
      - title: 
        url: "#"
        description: 
      - title: 
        url: "#"
        description: 
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "M.S. Word, powerpoint, Excel"
        skillrating: 90
      - skill: Gaussian Software
        skillrating: 80
      - skill: C, C++, Scilab, Fortran
        skillrating: 80
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Painting
      - hobby: Travelling
      - hobby: Cooking
      - hobby: Fiction reading